### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by jweiland1** [Virtual-FTC/Basic-Robot-Controller#4]
JW\
I could not install either “app”-they all downloaded 
Lenovo tablet= there was a problem parsing the package.
Ipad- the basicVRC stopped working (2 of 23)

**Comment by jweiland1** [comment]
Tried a Samsung Galaxy phone- The basic installed.

**Comment by jweiland1** [comment]
it works on phone'

**Comment by mihir-chauhan** [comment]
This problem should be fixed: Try downloading the latest APK from this link: https://github.com/Virtual-FTC/Basic-Robot-Controller/releases/download/v1.0/BasicVRC_App.apk
